server:
  port: 8090
springdoc:
  api-docs.path: /multi-database-usage-docs #open api custom name
spring:
  jackson:
    default-property-inclusion: non_null #if response field values are null, those will not be displayed
  application:
    name: spring-multi-datasource
  datasource:
    customer:
      jdbc-url: jdbc:mysql://localhost:3306/custdb
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    user:
      jdbc-url: jdbc:mysql://localhost:3306/userdb
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    post:
      url: jdbc:mysql://localhost:3306/postdb
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari: #database connection pool configuration
        connection-timeout: 15000
        minimum-idle: 2
        maximum-pool-size: 5
        idle-timeout: 10000
        max-lifetime: 50000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      transaction:
        jta:
          platform: null