spring.application.name=my-apache-camel-ms-2
server.port=8082
spring.activemq.broker-url=tcp://localhost:61616
camel.component.kafka.brokers=localhost:29092
#camel.component.kafka.bootstrap.servers=172.24.0.3:9092
#camel.component.kafka.configuration.socket.connection.setup.timeout.ms=60000
#camel.component.kafka.configuration.node.id=0
#camel.component.kafka.configuration.connections.max.idle.ms=30000


#logging.level.org.apache.camel=DEBUG
#logging.level.org.springframework=DEBUG