spring.application.name=my-apache-camel-ms-1

server.port=8081
spring.activemq.broker-url=tcp://localhost:61616
camel.component.kafka.brokers=localhost:29092
endpoint-for-logging=log:directendpoint1
timePeriod=10000
#spring boot standalone
#camel.springboot.main-run-controller=true
#camel.springboot.duration-max-seconds=60

#for camel debugging
#ogging.level.org.apache.camel=DEBUG
#logging.level.org.apache.camel.spring-boot=DEBUG
#logging.level.org.springframework.amqp.rabbit=DEBUG

#logging.level.org.apache.camel.component.kafka=DEBUG
#logging.level.org.apache.camel.component.kafka.consumer=DEBUG
#logging.level.org.apache.camel.component.kafka.producer=DEBUG
#logging.level.org.apache.kafka=DEBUG
#logging.level.org.apache.zookeeper=DEBUG



#camel.component.kafka.brokers=172.24.0.3:9092
#camel.component.kafka.bootstrap.servers=172.24.0.3:9092
#docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' my-kafka