server:
  port: 8091
logging:
  level:
    com.venkat.consumer: INFO

management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "ALWAYS"
spring:
  application:
    name: spring-kafka-consumer
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-sb-emp-id-4
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: com.venkat.consumer.deser.EmployeeDeserializer
      auto-offset-reset: earliest
      #properties:
        #spring:
          #json:
            #trusted:
              #packages: '*'

kafka:
  topic: emp-topic

